import { chromium } from 'playwright';
const BASE = 'https://flippeak.vercel.app';
const browser = await chromium.launch();
const page = await (await browser.newContext()).newPage();
await page.goto(`${BASE}/login`);
await page.getByLabel(/email/i).fill('qa15-1788911108995@flippeak.dev');
await page.getByLabel(/password/i).fill('FlipPeakQA15!');
await page.getByRole('button', { name: /sign in|login/i }).click();
await page.waitForTimeout(2_000);
await page.goto(`${BASE}/my-campaigns`);
await page.waitForLoadState('networkidle');
const text = await page.locator('main').innerText();
console.log('MY CAMPAIGNS CONTENT:', JSON.stringify(text.slice(0, 400)));
await page.screenshot({ path: 'qa-probe.png' });
await browser.close();
